pipeline {
    agent any
    environment {
        DOCKERHUB_CREDS = credentials('DevOps_lw2')
    }
    options {
        timestamps()
        skipDefaultCheckout(true)
    }
    stages {
        stage('Clone') {
            steps {
                cleanWs()
                bat 'git clone -b main https://github.com/DemonStage0/DevOps_lw2.git'
            }
        }
    }
}